# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e02456563f883394ae07bd8400213ee3d1d41191dea06cc9acb9ac7116d6dfba31c4b3f219ad1fdd1245447689fef3c8c26547f94b23dafd1bdc7d676197af

test:
  secret_key_base: 3488a46c64379202a548a3936a4c92ef2814d864d852390b694c57e329e029eaa152be89cda3b6ed2b426d4ae430b5f0eb77dc194bccc32db176af8e25c7391b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
